### ISSUE TITLE
Search button text

### ISSUE THREAD

**Issue by mrManner** [Scouterna/Scouterna-WPTheme#10]
No biggie, but ehrm…

http://d.pr/i/wsnx

**Comment by mrManner** [comment]
Oh, man kanske ska köra svenska wp ändå... #tankspridd

Stänger.

**Comment by sakjur** [comment]
Still a bug, the theme should be fully functional in both sv and en

**Comment by frozzare** [comment]
Bilden för sökknappen är bara gjord för att passa ordet "Sök", så man behöver fixa bilden så den går att repetera och fixa en css grej så kommer det se bra ut även för ordet "Search".

**Comment by sakjur** [comment]
men vad tusan. segt. det måste fungera med przeszukiwanie och αναζήτηση också

**Comment by mrManner** [comment]
Vore enklare att byta ut texten mot ett förstoringsglas... Inte riktigt lika bra funktionalitet, men ser snyggare ut.

**Comment by sakjur** [comment]
Jag vet inte. Explicit är bättre än implicit. Använder folk förstoringsglas för sökrutor i Uganda?

**Comment by frozzare** [comment]
Tycker nog inte att man ska byta ut texten till ett förstoringsglas utan köra på som de är idag men att fixa så man kan ha längre ord där. Annars börjar man frångå orginal designen mer och mer när man byter ut grejer och de är väl inte tanken? Tanken är väl att de ska vara ett fristående tema med fixar för grejer man upptäcker och fixar för buggar, de ska ändå likna de temat man får i Scouternas WordPress system.

**Comment by sakjur** [comment]
Absolut - som jag ser det så är det dock ingen strävan efter att få samma feature-set som Scouterna.se, utan ett fungerande tema som stilistiskt passar in i webbplattformen. Min syn på det hela är att det ska utvecklas mot stabilt tema som har möjligheterna att anpassas, är väldokumenterat och har innovativa funktioner som underlättar för admins.

Och såklart att temat inte gör någonting mer än är ett tema.

**Comment by frozzare** [comment]
Löst det med att göra bilden bredare och fixa lite css. https://github.com/frozzare/Scouterna-WPTheme/commit/c576780e65d4edaf857a797f37af8cf7049e9539 Dock tänkte jag inte på att göra branch av issue #8 så det blir knas om jag gör en pull reuqest nu förens min tidigare pull request är mergad. 

![](http://wp.forsmo.me/media/bild4.png)

**Comment by sakjur** [comment]
@frozzare Okej, mergade din förra, känns lite riskabelt utan hunnit testa, men wtf ;) :bowling:

**Comment by sakjur** [comment]
Fixed
