### ISSUE TITLE
Remove widget area "Right column – ads"?

### ISSUE THREAD

**Issue by mrManner** [Scouterna/Scouterna-WPTheme#12]
I'm not 100% sure, but it seems to be intended for the advertising plugins on scouterna.se/Scoutservice. And it's causing some [confusion](https://www.facebook.com/groups/scoutwebb/permalink/444466622332924/?comment_id=448043835308536&offset=0&total_comments=8).

**Comment by sakjur** [comment]
closed as won't fix.
